### ISSUE TITLE
How to convert saves for use in software emulators?

### ISSUE THREAD

**Issue by euan-forrester** [MiSTer-devel/WonderSwan_MiSTer#10]
Hello, I'm the author of savefileconverter.com (https://github.com/euan-forrester/save-file-converter) and I've been working on adding support for converting saves to and from MiSTer formats.

I was looking at WonderSwan saves on the MiSTer, and I noticed that the example saves I got were all `0x200` bytes larger than a power of 2. Looking at one example, for Rockman & Forte, I noticed what appeared to be a header containing the magic `Rbw0508_Ver1.00` at offset `0` and then `0x1A1B29` at offset `0x18`. I'm using the emulator mednafen, the default for OpenEmu.

Can you give me any guidance on what I should be adding and removing from WonderSwan (and WonderSwan Color) save files to convert them back and forth between a software emulator and the MiSTer format?

Thanks very much!

**Comment by RobertPeip** [comment]
Save files from Wonderswan contain one extra sector for RTC data at the end. You can probably just cut it off and use the save file that remains.

I haven't tried that yet, because i never used any savegame from this core in any emulator, but i think it should work.

Converting to Mister format should be the same: ignore the extra size and just rename the file from the emulator. The core should load it fine but RTC data is missing.

**Comment by euan-forrester** [comment]
Awesome, thank you!

For converting to the Mister format, I'm happy to pad out the file with `0x00` or `0xFF` or even random data for those final `0x200` bytes if that's somehow 'better' for the core. Does one of those make sense? Or should I just rename the emulator file and not pad it?

Also, are WonderSwan and WonderSwan Color the same from the perspective of save files? Or should I treat them differently somehow? I'm not very familiar with the WonderSwan, although it looks like a super cool machine!

**Comment by euan-forrester** [comment]
Fair enough, and thanks for trying it out!

I can get the local time from the browser -- if you could describe the format I could set it in the save file?

**Comment by RobertPeip** [comment]
Sorry, I totally forget about it...

The savegame can be loaded. Here is what is saved back from Mister after loading your savegame: 
[Rockman & Forte - Mirai Kara no Chousen Sha (J) [M][!].zip](https://github.com/MiSTer-devel/WonderSwan_MiSTer/files/8426263/Rockman.Forte.-.Mirai.Kara.no.Chousen.Sha.J.M.zip)

**Comment by euan-forrester** [comment]
No worries!

That's fantastic, and I was able to convert it back and load it again in the emulator, so it all seems to be working! Thank you!

Would it be possible for me to set the RTC information when converting the file to the MiSTer format? I can get information about the current time from the browser, so if you're able to describe the format I should be able to set it and save people the step of setting the clock.

**Comment by euan-forrester** [comment]
Thank you again for your help with this!

**Comment by RobertPeip** [comment]
Hey, I just closed this today as I thought it would be long solved.

If you still have anything you need, let me know.

**Comment by euan-forrester** [comment]
Yeah I saw the notification and it reminded me that I should have circled back and said thank you! It's all resolved and working great! Thanks for your help!
