### ISSUE TITLE
Can Tonpuusou get in-game?

### ISSUE THREAD

**Issue by FluBBaOfWard** [MiSTer-devel/WonderSwan_MiSTer#11]
I don't have a MiSTer yet but am developing a WonderSwan emulator myself.
Tonpuusou is one of the few games not starting for me, it seems the game expects HBlank timers to work without enabling them (Reg 0xA2). If my post is irrelevant, just close it.

**Comment by FluBBaOfWard** [comment]
Yes, that's how far I mean.
So I assume you don't care about TimerControl register (0xA2) then? If you do handle reg 0xA2 and the game works I need some serious work on my emulator.

**Comment by FluBBaOfWard** [comment]
In my debugging sessions I could only see Tonpuusou ever writing 0x00 to reg 0xA2 so something else  must be wrong with my emulator.
Thank you very much for the information and sorry for using this forum for questions.

**Comment by RobertPeip** [comment]
No worries :)
