### ISSUE TITLE
Would it be possible to put the test rom in their own repos?

### ISSUE THREAD

**Issue by FluBBaOfWard** [MiSTer-devel/WonderSwan_MiSTer#18]
@RobertPeip I have updated the timing test with more tests and made it more resilient to changes in the text file (Si & Di should always point to even addresses). I would be nice if the tests could have its own repo so one could do pull requests just for them.

**Comment by FluBBaOfWard** [comment]
Thanks, I put the repo here https://github.com/FluBBaOfWard/WSTimingTest
It might have a broken branch test right now but everything else should be correct.

**Comment by RobertPeip** [comment]
Ok, great. I think we can close this issue then?

If you need anything, you can still ask.

**Comment by FluBBaOfWard** [comment]
Yes, I close it now.
