### ISSUE TITLE
Audio crackle and visual noise with 75hz mode and sync to core enabled at 1440p

### ISSUE THREAD

**Issue by x0rtrunks** [MiSTer-devel/WonderSwan_MiSTer#7]
When trying to use 75hz mode there are green flickering pixels in the image and the sync will drop occasionally. 
Enabling sync to core will cause crackling audio.

Using 60hz with sync to core will cause audio distortion like the pitch is wrong plus warbling. Perhaps sync to core should be disabled option when using 60hz?

I should note that I am running at 1440p, so perhaps it's hitting the limits of the scaler?

**Comment by sorgelig** [comment]
1440p at 75hz is too high for pixel clock! It won't work reliably.

**Comment by x0rtrunks** [comment]
Thanks for confirming. I thought as much. I will try a lower resolution.
